### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by miguelcobain** [miguelcobain/ember-paper#3]
Here is my suggestion for the next components to develop. I think we should have the most essential features first. Please read #2 for contributing.

## Task list

- [x] Buttons (review)
- [ ] FAB buttons
- [x] Cards
- [x] Checkbox (review)
- [ ] Dialog
- [x] Material icons (google will release an official iconic font soon. Using unofficial font for now)
- [x] List (and possibly Divider)
- [x] List Controls
- [x] Radio Button (review)
- [x] Sidenav (not complete)
- [x] Slider
- [x] Switch (aka toggle in Polymer)
- [x] Progress Linear
- [x] Progress Circular
- [ ] Tabs
- [x] Menus
- [x] Inputs with errors, char counter, etc (currently only simple text field based on Polymer's)
- [x] Toolbar
- [x] Ripple effect (review. I think this could be improved.)
- [x] Shadow (review)
- [x] Normalize touch and mouse events (see `EventsMixin`). Checkboxes are not working in mobile, for example.
- [x] Flex layout (missing docs)
- [x] Autocomplete

I think that once we get all of these, we have a decent UI kit.
It would be great if we get everyone's effort into this.

**Comment by locks** [comment]
Hi, I wanna help. Are you on IRC/Gitter so we can coordinate better?

**Comment by stefanpenner** [comment]
> Check http://miguelcobain.github.io/ember-paper/#/textfield

those text fields are RAD!

**Comment by ef4** [comment]
I am happy to find this project! 

I'm actively adding capabilities to [liquid-fire](https://github.com/ef4/liquid-fire) to make it easy to support all the animation in Material Design, and I'd be happy to integrate them into `ember-paper` as they become ready.

And I'm doing a design-focused talk at EmberConf, and will definitely feature this repo.

**Comment by miguelcobain** [comment]
@ef4 I'm curious to see how ember-paper and liquid-fire would play along. Indeed, animations are a big part of material design specs. Having those integrated in ember-paper would be awesome!

I really see potential in this project. Material Design (besides being gorgeous!) solves so many UX problems/challenges. It would be a great step forward to back those solutions within a powerful environment like ember and ember-cli. It feels so natural. Ember components end up being an excellent way of encapsulating design.
There are so many things left to do.

Regarding your talk, tell me if you need anything. Would be glad if I could help. And please do share the slides/video. :D

**Comment by miguelcobain** [comment]
@locks Sure. Ping me on Twitter. Maybe gitter would be better so other people can follow!

**Comment by locks** [comment]
@miguelcobain já te pinguei :P

**Comment by miguelcobain** [comment]
Added list in 13f9e080845c4ff25b18f26998363c964e7c76da
Added dividers in ad9c2bdde9ad96a08faa3bd03c22d06c57770dc8

Check:
 - http://miguelcobain.github.io/ember-paper/#/list
 - http://miguelcobain.github.io/ember-paper/#/divider

Thanks @mansona!

**Comment by stefanpenner** [comment]
woohoo!

**Comment by BryanHunt** [comment]
@miguelcobain For the button wave effect, you might want to check out http://sgasser.github.io/ember-cli-materialize/#/buttons

**Comment by miguelcobain** [comment]
Switches now conform specs in d78fa263f1f6d0d574374e7a4e700498b6bd4af1

Check: http://miguelcobain.github.io/ember-paper/#/switch

**Comment by miguelcobain** [comment]
@BryanHunt Is there something wrong with the current ripple effect?

**Comment by BryanHunt** [comment]
@miguelcobain When I click a button, I see the background color change within a rounded rect and no animation.

![ember-paper_-_the_ember_approach_to_material_design_](https://cloud.githubusercontent.com/assets/504299/6135027/e7744c18-b12a-11e4-873b-dc0582740ba9.png)

When I click the button on ember-cli-materialize, I see the background change color in an animated effect from center to the edges (wave effect).

**Comment by nightexcessive** [comment]
Your task list seems to be missing the progress indicators.

That aside, awesome project. Thanks!

**Comment by miguelcobain** [comment]
Major bump.

Now with a decent Sidenav, Toolbars and Flex grid!
Thanks to @pixelhandler for the sidenav inspiration from [ember-off-canvas-components](https://github.com/pixelhandler/ember-off-canvas-components). Very smart use of custom events there.

Check: http://miguelcobain.github.io/ember-paper/
Still need to update docs...

**Comment by miguelcobain** [comment]
Cool blockless versions 07c800f756c9c0a09f8d6e7de66cfad7894223cd

**Comment by miguelcobain** [comment]
Icons. :heavy_check_mark: 

Check: http://miguelcobain.github.io/ember-paper/#/icons

**Comment by miguelcobain** [comment]
Added some simple cards on e9f81aeb82f0a79754f02ad41721e3ffb913bf28

Check: http://miguelcobain.github.io/ember-paper/#/card

**Comment by hhff** [comment]
Yoooooooo

I'm working on this http://www.google.com/design/spec/components/menus.html

**Comment by miguelcobain** [comment]
That will be a tough one!
Angular material select for inspiration: https://material.angularjs.org/#/demo/material.components.select

**Comment by mike1o1** [comment]
I submitted a pull request #88 for sliders. I'll work on converting tabs and fab buttons from [ember-material-design](https://github.com/mike1o1/ember-material-design) once you're ok with the slider.

**Comment by benedikt-d** [comment]
Regular Icon-Buttons would be nice!

**Comment by miguelcobain** [comment]
Sliders are up thanks to Mr. @mike1o1!

Check: http://miguelcobain.github.io/ember-paper/#/slider

**Comment by mansona** [comment]
I don't know if it's appropriate to mention a bug here (please let me know) but when I select one of the `Rating: /5 - demo of theming classes` sliders and hit right on the keyboard the slider decides to make it's way to Infinity :joy:

**Comment by mansona** [comment]
Dialogs: https://github.com/miguelcobain/ember-paper/pull/111

**Comment by mansona** [comment]
Paper-Dialog: https://github.com/miguelcobain/ember-paper/pull/116

**Comment by miguelcobain** [comment]
Cool list controls are ready:

http://miguelcobain.github.io/ember-paper/#/list-controls

We now have official material font icon and lots of updated styles.

**Comment by brandonjmckay** [comment]
nice one!

**Comment by miguelcobain** [comment]
> Inputs with errors, char counter, etc (currently only simple text field based on Polymer's)

Done via @DanMonroe 

Demo: http://miguelcobain.github.io/ember-paper/#/input

**Comment by miguelcobain** [comment]
Progress linear ported from ember material design by @peec 

Demo: http://miguelcobain.github.io/ember-paper/#/progress-linear

**Comment by miguelcobain** [comment]
Progress circular ported from ember material design by @peec

Demo: http://miguelcobain.github.io/ember-paper/#/progress-circular

**Comment by miguelcobain** [comment]
Paper autocomplete by @peec 

Demo: http://miguelcobain.github.io/ember-paper/#/autocomplete

**Comment by elwayman02** [comment]
Maybe this is a dumb question, but does this addon support any sort of responsive grid layouts?  I didn't see anything in the demos...

**Comment by miguelcobain** [comment]
@elwayman02 We're using angular material flex grid. There isn't any documentation on it yet.

For now you can understand its usage consulting [angular material] docs(https://material.angularjs.org/latest/#/layout/grid) and the demo page source code.

**Comment by DanChadwick** [comment]
This is now being tracked by #249. Closing unless there is some other reason to keep it open. :)
